version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./docker/conf/nginx:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx/
    links:
      - php
  php:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: food
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql